import { StaticPageShell } from '../components/legal/StaticPageShell'

export function TermsPage() {
  return (
    <StaticPageShell
      title="Terms of Service"
      subtitle="The terms that govern your use of PRLens."
      updated="July 10, 2026"
    >
      <p>
        These Terms of Service ("Terms") are a legal agreement between you (either an individual or
        an entity, "you") and PRLens ("PRLens", "we", "us", or "our") governing your access
        to and use of PRLens, including the dashboard, the webhook service, and the PRLens GitHub App
        (together, the "Service"). By creating an account, installing the PRLens GitHub App, or
        otherwise using the Service, you agree to be bound by these Terms. If you do not agree, do
        not use the Service.
      </p>

      <h2 id="the-service">1. Description of the Service</h2>
      <p>
        PRLens is an automated code review tool that analyzes the diffs of pull requests on
        repositories you connect, using a large language model to identify potential security,
        quality, performance, and style issues. It posts its findings back to GitHub as inline
        comments, a summary comment, a quality score, and a formal review verdict.
      </p>
      <p>
        PRLens is an assistive tool. It does not replace human code review, and its output — including
        scores, verdicts, and suggested fixes — is generated by an AI model and may be incomplete,
        inaccurate, or miss issues entirely. You remain solely responsible for the code you merge.
      </p>

      <h2 id="accounts">2. Accounts and access</h2>
      <ul>
        <li>
          You must sign in with a valid GitHub account to use the dashboard. You are responsible for
          maintaining the security of that account and for all activity that occurs through it.
        </li>
        <li>
          You must have the authority to install the PRLens GitHub App on any repository or
          organization you connect it to — for example, as the repository owner or an organization
          administrator with app-installation permissions.
        </li>
        <li>
          You may disconnect a repository or revoke the GitHub App's access at any time, either from
          the dashboard or directly from your GitHub account's Applications settings.
        </li>
      </ul>

      <h2 id="acceptable-use">3. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service on repositories you do not have the right to grant access to.</li>
        <li>
          Attempt to circumvent, disable, or interfere with the Service's security features,
          including webhook signature verification or authentication mechanisms.
        </li>
        <li>
          Use the Service to submit content that is unlawful, infringing, or that you do not have
          the right to submit for automated processing.
        </li>
        <li>
          Reverse engineer, decompile, or attempt to extract the underlying prompts, models, or
          source code of the Service, except to the extent such restriction is prohibited by
          applicable law.
        </li>
        <li>
          Use the Service to build a competing product, or resell or sublicense access to the
          Service without our prior written consent.
        </li>
        <li>
          Send excessive or automated traffic intended to degrade the Service's availability for
          other users.
        </li>
      </ul>
      <p>
        We may suspend or terminate access for any account or installation we reasonably believe is
        in violation of this section.
      </p>

      <h2 id="third-party">4. Third-party services</h2>
      <p>
        The Service relies on third-party providers, including GitHub (for authentication, repository
        access, and posting review output) and Microsoft Azure OpenAI (for AI-generated analysis).
        Your use of the Service is also subject to GitHub's own Terms of Service and any applicable
        GitHub Marketplace or GitHub App terms. We are not responsible for outages, changes, or
        limitations imposed by these third-party providers that affect the Service.
      </p>

      <h2 id="intellectual-property">5. Intellectual property</h2>
      <p>
        We retain all rights, title, and interest in and to the Service, including its software,
        design, and branding. You retain all rights to your own source code and repositories; we
        claim no ownership over your code. We are granted only the limited right to process your pull
        request diffs as necessary to provide the Service, as described in our{' '}
        <a href="/privacy">Privacy Policy</a>.
      </p>

      <h2 id="no-warranty">6. No warranty</h2>
      <p>
        THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTIES OF ANY KIND, WHETHER
        EXPRESS, IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF
        MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT
        THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE, OR THAT ITS ANALYSIS,
        SCORES, OR SUGGESTIONS WILL BE ACCURATE, COMPLETE, OR SUITABLE FOR ANY PARTICULAR PURPOSE.
        YOU ARE SOLELY RESPONSIBLE FOR REVIEWING AND VALIDATING ANY CODE BEFORE MERGING OR DEPLOYING
        IT, REGARDLESS OF THE SERVICE'S OUTPUT.
      </p>

      <h2 id="limitation-of-liability">7. Limitation of liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, PRLENS AND ITS CONTRIBUTORS WILL NOT BE LIABLE
        FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF
        PROFITS, DATA, OR GOODWILL, ARISING FROM OR RELATED TO YOUR USE OF THE SERVICE, INCLUDING
        DAMAGES RESULTING FROM CODE MERGED IN RELIANCE ON THE SERVICE'S OUTPUT, EVEN IF WE HAVE BEEN
        ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OUR TOTAL AGGREGATE LIABILITY ARISING OUT OF OR
        RELATED TO THESE TERMS OR THE SERVICE WILL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU
        PAID US FOR THE SERVICE IN THE 12 MONTHS PRECEDING THE CLAIM, OR (B) ONE HUNDRED US DOLLARS
        (USD $100).
      </p>
      <p>
        Some jurisdictions do not allow the exclusion or limitation of certain damages, so some of the
        above limitations may not apply to you.
      </p>

      <h2 id="indemnification">8. Indemnification</h2>
      <p>
        You agree to indemnify and hold PRLens harmless from any claims, damages, liabilities,
        and expenses (including reasonable legal fees) arising out of your use of the Service, your
        violation of these Terms, or your violation of any rights of a third party.
      </p>

      <h2 id="termination">9. Termination</h2>
      <p>
        You may stop using the Service at any time by disconnecting your repositories, revoking the
        GitHub App's access, and deleting your account. We may suspend or terminate your access to
        the Service, in whole or in part, at any time — with notice where practical — if you violate
        these Terms, if required by law, or if we discontinue the Service. Sections that by their
        nature should survive termination (including Intellectual Property, No Warranty, Limitation
        of Liability, and Indemnification) will survive.
      </p>

      <h2 id="changes-to-terms">10. Changes to these Terms</h2>
      <p>
        We may update these Terms from time to time. If we make material changes, we will update the
        "Last updated" date above and, where appropriate, notify you through the dashboard.
        Continued use of the Service after a change takes effect constitutes acceptance of the
        updated Terms.
      </p>

      <h2 id="governing-law">11. Governing law</h2>
      <p>
        These Terms are governed by the laws applicable in the operator's jurisdiction of
        residence, without regard to conflict-of-laws principles, except where mandatory local
        consumer protection law provides otherwise for users located in the EEA or UK.
      </p>

      <h2 id="contact-tos">12. Contact us</h2>
      <p>
        Questions about these Terms can be sent to{' '}
        <a href="mailto:support@prlens.dev">support@prlens.dev</a>.
      </p>
    </StaticPageShell>
  )
}
